###########
# site.url, site.title

url:   'http://stabbycykel.github.io'
title: 'Stabby cykelverkstad'
google_analytics: 'UA-60538504-1'


########
# more settings

# markdown: redcarpet
# highlighter: pygments
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

markdown: redcarpet
pygments: true

sass:
  sass_dir: css
  style:    expanded



exclude:
- README.md


safe: true
lsi: false
